config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'reviews/create'
  devise_for :users
  root to: "pages#home"
  get "about-us", to: "pages#about-us", as: :about_us
  get "up_next", to: "pitches#up_next", as: :up_next
  get "privacy-policy", to: "pages#privacy-policy", as: :privacy_policy
  match "/404", to: "errors#not_found", via: :all


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :pitches do
    member do
      get :generate_ppt
      get 'up_next'
    end
    resources :reviews, only: [:create]
    resources :favourites, only: [:create]
  end

  resources :favourites, only: [:index, :destroy]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :pitch
  belongs_to :user
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }

  def content
    #client = OpenAI::Client.new
    #chatgpt_response = client.chat(parameters: {
    #  model: "gpt-4o-mini",
    #  messages: [
    #    { role: "user", content: "We are creating a presentation called #{name} based on #{description}. Generate 4 bullet points describing the potential problems/pain points for the second slide. Generate 4 bullet points describing the target audience for the third slide. Generate 4 bullet points describing the solution for the fourth slide. Do not include any introductory phrases like 'Here are the points'—just the bullet points." }
    #  ]
    #})
    #return chatgpt_response["choices"][0]["message"]["content"]
    "Pain point 1\nPain point 2\nPain point 3\nPain point 4\nAudience point 1\nAudience point 2\nAudience point 3\nAudience point 4\nSolution point 1\nSolution point 2\nSolution point 3\nSolution point 4"

  end

  def related_image
    fetcher = ImageFetcher.new(name)
    fetcher.fetch_image
  end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :pitch

  validates :comment, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :pitches
  has_many :favourites
  has_one_attached :photo

  validates :user_name, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404

  def render_404
    redirect_to "/404"
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :first_name, :last_name])
  end

end


# rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  # def record_not_found
  #   render template: "errors/not_found", status: 404
  # end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render template: "errors/not_found", status: 404
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @favourites = current_user.favourites.includes(:pitch)
  end

  def create
    @pitch = Pitch.find(params[:pitch_id])
    @favourite = current_user.favourites.new(pitch: @pitch)
    @favourite.pitch = @pitch
    if @favourite.save
      redirect_to pitch_path(@pitch), notice: 'pitch added to favourites!'
    else
      redirect_to pitch_path(@pitch), alert: 'Unable to add pitch to favourites.'
    end
  end

  def new
  end

  def show
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    redirect_to favourites_path, notice: 'Pitch removed from favourites.'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about_us
  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  before_action :set_pitch, only: [:show, :destroy]

  def index
    @pitches = Pitch.all
  end

  def create
    @pitch = Pitch.new(pitch_params)
    @pitch.user = current_user
    if @pitch.save
      redirect_to pitch_path(@pitch)
    else
      render :new
    end
  end

  def new
    @pitch = Pitch.new
  end

  def show
    if !current_user
      redirect_to pitches_path
      return
    end
    @review = Review.new
    @favourite = Favourite.new
    @favourites = Favourite.all
    unless @pitch.pain_points.present?
      @pitch.update(pain_points: @pitch.content)
    end
    unless @pitch.target_audience.present?
      @pitch.update(target_audience: @pitch.content)
    end
    unless @pitch.solution.present?
      @pitch.update(solution: @pitch.content)
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @pitch.destroy
    redirect_to pitches_path, status: :see_other
  end

  def generate_ppt
    @pitch = Pitch.find(params[:id])
    ppt_file = create_ppt(@pitch)
    send_file ppt_file, type: "application/vnd.openxmlformats-officedocument.presentationml.presentation", filename: "#{@pitch.name.parameterize}.pptx"
  end

  private

  def set_pitch
    @pitch = Pitch.find(params[:id])
  end

  def pitch_params
    params.require(:pitch).permit(:name, :description, :photo, :template )
  end

  def create_ppt(pitch)
    ppt = Powerpoint::Presentation.new
    # ppt.add_textual_slide(@pitch.name)
    ppt.add_textual_slide("Pain Points", @pitch.content.split("\n")[0..3])
    ppt.add_textual_slide("Target Audience", @pitch.content.split("\n")[4..7])
    ppt.add_textual_slide("Solution", @pitch.content.split("\n")[8..11])
    file_path = Rails.root.join('tmp', "#{@pitch.name.parameterize}.pptx")
    ppt.save(file_path)

    file_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @pitch = Pitch.find(params[:pitch_id])
    @review = Review.new(review_params)
    @review.pitch = @pitch
    if @review.save
      redirect_to pitch_path(@pitch)
    else
      render 'pitches/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def show
  end

  def edit
    # @user = current_user # makes sure we are editing the current user
  end

  def update
    # @user = current_user # makes sure we are updating the current user
    # if @user.update(user_params) # if the user is updated successfully
    #   redirect_to edit_user_registration_path, notice: 'Account updated successfully' # redirect to the user's profile page
    # else
    #   render :edit # if the user is not updated successfully, render the edit page again
    # end
  end

  def destroy
  end

  # private

  # def user_params # strong parameters
  #   # params.require(:user).permit(:email, :password, :password_confirmation) # only allow these parameters to be updated
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favourites/destroy.html.erb
<h1>Favourites#destroy</h1>
<p>Find me in app/views/favourites/destroy.html.erb</p>

app/views/favourites/index.html.erb
<div class="container" style="min-height: 100vh;">
  <h1 class="text-center mb-4">My Favourites💜</h1>
  <% @favourites.each do |favourite| %>
    <div class="card-pitch">
      <div id="carousel-<%= favourite.id %>" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" style="height: 100%;">
            <div class="d-flex justify-content-center align-items-center w-100 h-100">
              <div class="w-100 h-100 d-flex flex-column justify-content-center align-items-center"
                    style="border-radius: 10px;
                            background-image: url('<%= favourite.pitch.template.present? && File.exist?(Rails.root.join('app/assets/images/templates', "#{favourite.pitch.template}_title.JPG")) ? asset_path("templates/#{favourite.pitch.template}_title.JPG") : asset_path('templates/bright_modern_title.JPG') %>');
                            background-size: cover;
                            background-position: center;
                            background-repeat: no-repeat;
                            min-height: 50vh">

                <h4 class="<%= ['dark_modern', 'focus', 'marina'].include?(favourite.pitch.template) ? 'text-white' : 'text-black' %> text-center mb-4" style="font-size: 3rem; font-weight: bold;">
                <%= favourite.pitch.name %>
                </h4>

                <div class="text-center">
                  <% if favourite.pitch.image_url.present? %>
                    <%= image_tag favourite.pitch.image_url, alt: favourite.pitch.name, class: "img-fluid rounded", style: "max-width: 300px; height: auto;" %>
                  <% elsif favourite.pitch.photo.attached? %>
                    <%= cl_image_tag favourite.pitch.photo.key, height: 200, width: 300, crop: :fill, class: "rounded" %>
                  <% else %>
                    <img src="<%= asset_path('fullsize/1.jpg') %>" alt="..." class="img-fluid rounded" style="max-width: 300px; height: auto;">
                  <% end %>
                </div>

              </div>
            </div>
          </div>


          <div class="carousel-item">
            <div class="d-flex justify-content-center">
              <div class="w-100 h-100 d-flex flex-column justify-content-center align-items-center"
                  style="border-radius: 10px;
                          background-image: url('<%= favourite.pitch.template.present? && File.exist?(Rails.root.join('app/assets/images/templates', "#{favourite.pitch.template}_content.JPG")) ? asset_path("templates/#{favourite.pitch.template}_content.JPG") : asset_path('templates/bright_modern_content.JPG') %>');

                          background-size: cover;
                          background-position: center;
                          min-height: 50vh">
                  <h5 class="<%= ['dark_modern', 'focus', 'marina'].include?(favourite.pitch.template) ? 'text-white' : 'text-black' %> text-center mb-3">PAIN POINTS</h5>
                <ul class="list-unstyled <%= ['dark_modern', 'focus', 'marina'].include?(favourite.pitch.template) ? 'text-white' : 'text-black' %>">
                  <%= favourite.pitch.pain_points.split("\n")[0..3].map { |point| "<li>#{point.strip}</li>" }.join.html_safe %>
                </ul>
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="d-flex justify-content-center">
              <div class="w-100 h-100 d-flex flex-column justify-content-center align-items-center"
                  style="border-radius: 10px;
                          background-image: url('<%= favourite.pitch.template.present? && File.exist?(Rails.root.join('app/assets/images/templates', "#{favourite.pitch.template}_content.JPG")) ? asset_path("templates/#{favourite.pitch.template}_content.JPG") : asset_path('templates/bright_modern_content.JPG') %>');

                          background-size: cover;
                          background-position: center;
                          min-height: 50vh">
                  <h5 class="<%= ['dark_modern', 'focus', 'marina'].include?(favourite.pitch.template) ? 'text-white' : 'text-black' %> text-center mb-3">TARGET AUDIENCE</h5>
                <ul class="list-unstyled <%= ['dark_modern', 'focus', 'marina'].include?(favourite.pitch.template) ? 'text-white' : 'text-black' %>">
                  <%= favourite.pitch.target_audience.split("\n")[4..7].map { |point| "<li>#{point.strip}</li>" }.join.html_safe %>
                </ul>
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="d-flex justify-content-center">
              <div class="w-100 h-100 d-flex flex-column justify-content-center align-items-center"
                  style="border-radius: 10px;
                          background-image: url('<%= favourite.pitch.template.present? && File.exist?(Rails.root.join('app/assets/images/templates', "#{favourite.pitch.template}_content.JPG")) ? asset_path("templates/#{favourite.pitch.template}_content.JPG") : asset_path('templates/bright_modern_content.JPG') %>');

                          background-size: cover;
                          background-position: center;
                          min-height: 50vh">
                  <h5 class="<%= ['dark_modern', 'focus', 'marina'].include?(favourite.pitch.template) ? 'text-white' : 'text-black' %> text-center mb-3">SOLUTION</h5>
                <ul class="list-unstyled <%= ['dark_modern', 'focus', 'marina'].include?(favourite.pitch.template) ? 'text-white' : 'text-black' %>">
                  <%= favourite.pitch.solution.split("\n")[8..11].map { |point| "<li>#{point.strip}</li>" }.join.html_safe %>
                </ul>
              </div>
            </div>
          </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= favourite.id %>" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true" style="background-color: 670BFF;"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= favourite.id %>" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true" style="background-color: 670BFF;"></span>
          <span class="visually-hidden">Next</span>
        </button>
        </div>
      <div class="container mb-5">
        <div class="card shadow p-2" style="width: 100%;">
          <h5><strong>Name:</strong><%= favourite.pitch.name %></h5>
          <p><strong>Description:</strong> <%= favourite.pitch.description %></p>
          <div class="d-flex justify-content-end">
            <%= link_to favourite_path(favourite), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove this from your favourites?" }, class: "btn btn-primary btn-sm" do %>
              <i class="fas fa-trash-alt"></i>
              <% end %>
          </div>
        </div>
      </div>
      </div>
    </div>
  <% end %>
</div>

app/views/favourites/new.html.erb
<h1>Favourites#new</h1>
<p>Find me in app/views/favourites/new.html.erb</p>

app/views/favourites/show.html.erb
<h1>Favourites#show</h1>
<p>Find me in app/views/favourites/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PitchPerfect</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  </head>

  <body class="d-flex flex-column min-vh-100">
    <header>
      <%= render "shared/navbar" %>
    </header>

    <main class="flex-grow-1">
      <%= yield %>
    </main>

    <footer>
      <%= render "shared/footer" %>
    </footer>

    <script>
      function scrollDown() {
        window.scrollBy({
          top: window.innerHeight * 1.1,
          behavior: "smooth"
        });
      }

      document.getElementById('copy-link').addEventListener('click', function(event) {
        event.preventDefault();
        navigator.clipboard.writeText('<%= request.original_url %>').then(function() {
          alert('Link copied to clipboard!');
        }).catch(function(err) {
          alert('Failed to copy the link: ' + err);
        });
      });
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta property="og:title" content="Perfect Pitch - Your Business Idea, Perfectly Pitched">
    <meta property="og:image" content="facebook-card.jpg">
    <meta property="og:description" content="Perfect Pitch is a Le Wagone Alumnus Capstone Project. It is by design an opensource project for Le Wagon Bootcamp Alumni to continue their journey and practice their coding skills.">
    <meta property="og:site_name" content="Perfect Pitch">
    <meta name="facebook-domain-verification" content="xkvkqa13bc155z19l17cihfl46winw">
  </head>
  <body>
    <div class="landing-page" style="background-image: linear-gradient(rgba(255,255,255,0.8),rgba(255,255,255,0.8)), url(<%= asset_path 'background-image.png' %>); background-size: cover; height: 100vh; display: flex; justify-content: center; align-items: center; text-align: center;">
      <div class="content">
        <h1>Your Business Idea, Perfectly Pitched</h1>
        <h2 style="color: #A259FF;">Turn Your Vision Into A Winning Pitch - Instantly</h2>
        <div class="d-flex justify-content-center gap-3 mt-4">
          <%= link_to "Generate Pitch", new_pitch_path, class: "btn btn-primary" %>
          <%= link_to "Explore Public Pitches", pitches_path, class: "btn btn-secondary" %>
        </div>
      </div>
    <%= render "shared/scroll_arrow" %>
    </div>
    <div class="how-it-works text-center" style="color: #670BFF; height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center;">
      <h2 class="section-title" style="margin-bottom: 30px;">How It Works</h2>
      <div class="row justify-content-center">
        <div class="col-12 col-md-4 step-card d-flex flex-column align-items-center">
          <i class="bi-pencil-square fs-1" style="color: #670BFF;"></i>
          <div style="background-color: #A259FF; color: white; padding: 20px; border-radius: 8px; width: 80%; height: 185px;">
            <h3>Step 1: Enter Your Idea</h3>
            <p class="section-text">Simply input your business concept in a few words.</p>
          </div>
        </div>
        <div class="col-12 col-md-4 step-card d-flex flex-column align-items-center">
          <i class="bi-lightbulb fs-1" style="color: #670BFF;"></i>
          <div style="background-color: #A259FF; color: white; padding: 20px; border-radius: 8px; width: 80%; height: 185px;">
            <h3>Step 2: AI Generates a Pitch</h3>
            <p class="section-text">Our smart AI crafts a compelling pitch instantly.</p>
          </div>
        </div>
        <div class="col-12 col-md-4 step-card d-flex flex-column align-items-center">
          <i class="bi-rocket fs-1" style="color: #670BFF;"></i>
          <div style="background-color: #A259FF; color: white; padding: 20px; border-radius: 8px; width: 80%; height: 185px">
            <h3>Step 3: Present with Confidence</h3>
            <p class="section-text">Use your pitch to impress investors and audiences.</p>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-center mt-4">
        <%= link_to "Register Now", new_user_registration_path, class: "btn btn-primary" %>
      </div>
      <%= render "shared/scroll_arrow" %>
    </div>
    <section class="why-choose text-center mt-5" style="background-image: linear-gradient(rgba(255,255,255,0.8),rgba(255,255,255,0.8)), url(<%= asset_path 'background-image.png' %>); background-size: cover; color: #670BFF; height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center;">
      <h2 class="section-title">Why Choose Perfect-Pitch?</h2>
      <div class="row justify-content-center">
        <div class="col-12 col-md-4 feature-card d-flex flex-column align-items-center">
          <i class="bi-gem fs-1" style="color: #670BFF;"></i>
          <div style="background-color: #A259FF; color: white; padding: 20px; border-radius: 8px; width: 80%; min-height: 150px;">
            <h3>Instant, High-Quality Pitches</h3>
            <p class="section-text">No more struggling with wording.</p>
          </div>
        </div>
        <div class="col-12 col-md-4 feature-card d-flex flex-column align-items-center">
          <i class="bi-laptop fs-1" style="color: #670BFF;"></i>
          <div style="background-color: #A259FF; color: white; padding: 20px; border-radius: 8px; width: 80%; min-height: 150px;">
            <h3>Persuasive & Professional</h3>
            <p class="section-text">Your idea deserves the spotlight.</p>
          </div>
        </div>
        <div class="col-12 col-md-4 feature-card d-flex flex-column align-items-center">
          <i class="bi-globe fs-1" style="color: #670BFF;"></i>
          <div style="background-color: #A259FF; color: white; padding: 20px; border-radius: 8px; width: 80%; min-height: 150px;">
            <h3>Tailored to Your Needs</h3>
            <p class="section-text">Short and snappy elevator pitch.</p>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-center mt-4">
        <%= link_to "Generate Pitch", new_pitch_path, class: "btn btn-primary" %>
      </div>
    </section>
  </body>
</html>

app/views/pitches/create.html.erb
<h1>Pitches#create</h1>
<p>Find me in app/views/pitches/create.html.erb</p>

app/views/pitches/destroy.html.erb
<h1>Pitches#destroy</h1>
<p>Find me in app/views/pitches/destroy.html.erb</p>

app/views/pitches/edit.html.erb
<h1>Pitches#edit</h1>
<p>Find me in app/views/pitches/edit.html.erb</p>

app/views/pitches/new.html.erb
<div class="container mt-5" style="width: 50%; justify-content: center; align-items: center">
  <h1>Create a New Pitch</h1>
    <%= simple_form_for @pitch do |f| %>
        <%= f.input :name, label: "Pitch Name", input_html: { class: "form-control" } %>

        <%= f.input :description, label: "Pitch Description", as: :text, input_html: { class: "form-control", rows: 4 } %>

        <%= f.input :photo, label: "Pitch Display Image", as: :file %>

        <%= f.label :template, "Choose a Template" %>
        <%= f.select :template, options_for_select(["bright_modern", "dark_modern","focus", "geometric", "marina", "momentum", "shift"]), {}, class: "form-select" %>

        <div data-controller="loading-spinner" data-action="click->loading-spinner#show" class="buttons mt-5">
          <div id="spinner" data-loading-spinner-target="spinner" style="display: none;">
            <img src="<%= asset_path('waiting.gif') %>" alt="Loading..." />
          </div>
          <%= f.submit "Create Pitch", class: "btn btn-primary" %>
          <%= link_to 'Back to Pitches', pitches_path, class: "btn btn-secondary" %>
        </div>
    <% end %>
</div>

app/views/pitches/update.html.erb
<h1>Pitches#update</h1>
<p>Find me in app/views/pitches/update.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    <p>© 2025 Perfect Pitch. All Rights Reserved. </p>
  </div>


<div class="footer-links">
    <h3>Follow Us</h3><br>
    <a href="https://www.facebook.com" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://www.linkedin.com" target="_blank"><i class="fab fa-linkedin"></i></a>
    <a href="https://www.instagram.com" target="_blank"><i class="fab fa-instagram"></i></a>
</div>



<div class="footer-menu">
    <%= link_to 'TOS & Privacy', privacy_policy_path %><br>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color:#670BFF;">
  <div class="container-fluid">
    <div class="d-flex align-items-center">

      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "Heading bg.png" %>
      <% end %>
      <%= link_to "PERFECT PITCH", "#", class: "nav-link text-white" %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to pitches_path, class: "nav-link text-white" do %>
            <i class="fas fa-home"></i>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Generate Pitch", new_pitch_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar text-black" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.pic_url.present? %>
                  <%= image_tag current_user.pic_url, class: "avatar", alt: "dropdown menu" %>
                <% else %>
                  <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4YreOWfDX3kK-QLAbAL4ufCPc84ol2MA8Xg&s", class: "avatar", alt: "dropdown menu" %>
                <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", edit_user_registration_path, class: "dropdown-item text-black" %>
              <%= link_to "My Pitches", pitches_path, class: "dropdown-item text-black" %>
              <%= link_to "My Favourites", favourites_path, class: "dropdown-item text-black" %>
              <%= link_to "About Us", about_us_path, class: "dropdown-item text-black" %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item text-black" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_scroll_arrow.html.erb
<div class="scroll-down-wrapper">
  <div class="scroll-down-arrow" onclick="scrollDown()">
    <div class="arrow"></div>
  </div>
</div>